import React, { Component } from 'react';
import ExpansionPanel from '@material-ui/core/ExpansionPanel';
import ExpansionPanelSummary from '@material-ui/core/ExpansionPanelSummary';
import ExpansionPanelDetails from '@material-ui/core/ExpansionPanelDetails';
import Typography from '@material-ui/core/Typography';
import ExpandMoreIcon from '@material-ui/icons/ExpandMore';
import { Avatar, Grid, Fab, Paper } from '@material-ui/core';
import EditInspection from './editInspection';
import Enums from '../../../helpers/Enums';
import Delete from '@material-ui/icons/Delete';
import Edit from '@material-ui/icons/Edit';
import Divider from '@material-ui/core/Divider';
